name: E2E Tests

on: 
    push:
        branches: [main]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: cypress-io/github-action@v5

            with: 
                record: true
            env: 
                CYPRESS_RECORD_KEY: 13f10427-ebf3-466b-a67e-430330db0b9d